new file: src/downloadcontent.py
shlomif/python-vnu_validator pull request #6
Opened 2021-11-22 17:01 UTC by sergiomb2

draft for #5

2021-11-23 15:24 UTC, shlomif commented
@sergiomb2 : see my comments.

2021-11-23 20:31 UTC, sergiomb2 commented
> @sergiomb2 : see my comments.

where ?

2021-11-24 06:25 UTC, shlomif commented
> > @sergiomb2 : see my comments.
> 
> where ?

my code review comments on https://github.com/shlomif/python-vnu_validator/pull/6/files . Thanks!

2021-11-24 10:33 UTC, sergiomb2 commented
![image](https://user-images.githubusercontent.com/1143630/143222065-2c1aa982-5c44-4422-898b-60e1169fc2fb.png)

2021-11-24 12:18 UTC, shlomif requested changes
See my comments,

2021-11-24 12:18 UTC, shlomif commented on src/vnu_validator/__init__.py
> +        url, content, text_aux = downloadcontent(self.path)
Perhaps extract a `fetch_path()` method, a base class and two child classes. i'd rather not conflate https fetching w local files

2021-11-24 12:18 UTC, shlomif commented on src/vnu_validator/__init__.py
> +from vnu_validator.downloadcontent import downloadcontent
Please localize this import.

2021-11-24 12:18 UTC, shlomif commented on src/vnu_validator/downloadcontent.py
> +def downloadcontent(url, extras = {}, log = None):
this is generic enough to be its own pypi dist

2021-11-24 12:18 UTC, shlomif commented on src/vnu_validator/downloadcontent.py
> +if __name__ == '__main__':
all of this and its imports doesnt belong here.

2021-11-24 12:18 UTC, shlomif commented on src/vnu_validator/downloadcontent.py
> +            extras = eval (argv[2])
"eval()"? god help me...

2021-11-24 12:20 UTC, shlomif commented
@sergiomb2 : see my comments.

> ![image](https://user-images.githubusercontent.com/1143630/143222065-2c1aa982-5c44-4422-898b-60e1169fc2fb.png)
> 
> I don't see it !

Hope it is ok now. Stupid github UI: https://www.shlomifish.org/philosophy/books-recommends/#design_of_everyday_things

2021-11-26 10:08 UTC, shlomif commented
@sergiomb2 : hi! it should be ok now. Did you read my comments? Please confirm.

2021-11-26 10:25 UTC, sergiomb2 commented
yes I read your comments , this weekend (tomorrow and after tomorrow) I will improve my commit ,
I will replace eval with  json.loads(x) , I think

2021-11-26 11:00 UTC, shlomif commented
> yes I read your comments , this weekend (tomorrow and after tomorrow) I will improve my commit , I will replace eval with json.loads(x) , I think

Gotcha. I think the whole `main()` section can be removed altogether.

2021-12-10 12:40 UTC, shlomif commented
@sergiomb2 any news?

2021-12-17 12:09 UTC, shlomif commented
Rejecting for now, to avoid clutter.

2021-12-17 12:09 UTC, closed without merging